### PR TITLE
Update aup.md

### PR DESCRIPTION
**Pull request by forageddev**

### CODE REVIEW

**Comment by ohemilyy** [comment]
fuck off forged

**Comment by forageddev** [comment]
FORAGED

**Comment by ohemilyy** [comment]
ratio

**Comment by Dannnington** [comment]
Hi there! Thanks for submitting a Pull Request to the repository. We aren't accepting new additions to our legal documents from the general public for the most part, as this repository is mostly a mirror of our internal equivalents.

Have a good day!

**Pull request closed without merging**
